node:internal*events*shared_internal_event_emitter:*
    throw er; * Unhandled 'error' event
    ^

Error
    at Object.<anonymous> (*events_unhandled_error_subclass.js:*:*)
Emitted 'error' event on Foo instance at:
    at Object.<anonymous> (*events_unhandled_error_subclass.js:*:*)

Node.js *
